
export const GAME_SET_STATE = 'SET_GAME_STATE'
export const GAME_CHOOSE_ACTION = 'GAME_CHOOSE_ACTION'
export const GAME_UPDATE_SCORE = 'GAME_UPDATE_SCORE'
export const GAME_UPDATE_CURRENT = 'GAME_UPDATE_CURRENT'
export const GAME_REDUCE_TIME_LEFT = 'GAME_REDUCE_TIME_LEFT'
export const GAME_RESET = 'GAME_RESET'
export const GAME_ADD_USER_ANSWER = 'GAME_ADD_USER_ANSWER'
